"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.oceanDark = exports.oceanLight = exports.classicDark = exports.classicLight = void 0;
const classicLight_1 = require("./classicLight");
Object.defineProperty(exports, "classicLight", { enumerable: true, get: function () { return classicLight_1.classicLight; } });
const classicDark_1 = require("./classicDark");
Object.defineProperty(exports, "classicDark", { enumerable: true, get: function () { return classicDark_1.classicDark; } });
const oceanLight_1 = require("./oceanLight");
Object.defineProperty(exports, "oceanLight", { enumerable: true, get: function () { return oceanLight_1.oceanLight; } });
const oceanDark_1 = require("./oceanDark");
Object.defineProperty(exports, "oceanDark", { enumerable: true, get: function () { return oceanDark_1.oceanDark; } });
